language: cpp

before_install:
    - sudo apt-get-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-default

script:
    - qmake -qt=qt5
    - make
