language: cpp

before_install:
    - sudo apt-add-repository -y ppa:beineri/opt-qt521
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt52-meta-full

script:
    - qmake --version
    - qmake 
    - make
