language: cpp

before_install:
    - sudo apt-add-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-default

script:
    - qmake --version
    - qmake 
    - make
